### ISSUE TITLE
Update site for 0.10.9.5 contains corrupt content.xml file

### ISSUE THREAD

**Issue by lwrage** [py4j/py4j-eclipse-udpate-site#2]
Line 106 is not valid xml
`    <name='version.Py4J' version='1.0.0.07I7GcKCAvE7C2EcH1SyXe8u'>`
It should be something like
`    <unit id='<whatever the correct ID is>' version='1.0.0.07I7GcKCAvE7C2EcH1SyXe8u'>`

**Comment by bartdag** [comment]
@lwrage can you try it again? I tried to automate the process but there was a bug in the sed command.

**Comment by lwrage** [comment]
I see that content.jar is new, but the contained content.xml still has the same error.

**Comment by bartdag** [comment]
rrr... hopefully this should be fixed now (instead of `<name=` it was `<unit=` and now it is `<unit id=`)

**Comment by lwrage** [comment]
My build works. Thanks for fixing this so quickly.
